language: java
jdk:
 - openjdk8

branches:
 only:
  - master

# Travis CI 서버의 Home
cache:
 directories:
  - '$HOME/.m2/repository'
  - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
 - zip -r springboot *
 - mkdir -p deploy
 - mv springboot.zip deploy/springboot.zip

deploy:
  - provider: s3
    access_key_id: AKIATT55DVO6BFTVWADM
    secret_access_key: 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
    bucket: springboot2-webservice-build2
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: AKIATT55DVO6BFTVWADM
    secret_access_key: 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
    bucket: springboot2-webservice-build2
    key: springboot.zip
    bundle_type: zip
    application: springboot2-webservice
    deployment_group: springboot2-webservice-group
    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행 완료 시 메일로 알람
notifications:
 email:
  recipients:
   - gogoadl@naver.com

